name: Schedule update for other branches
'on':
  schedule:
  - cron: 0 12 * * SAT
permissions:
  contents: read
  actions: write
defaults:
  run:
    shell: bash
jobs:
  prepare:
    name: Compute list of branches
    runs-on: ubuntu-latest
    if: github.repository == 'nix-community/nixvim'
    outputs:
      branches: ${{ steps.list-branches.outputs.result }}
    steps:
    - name: Checkout version-info
      uses: actions/checkout@v6
      with:
        sparse-checkout: version-info.toml
        sparse-checkout-cone-mode: false
    - name: List stable branches
      id: list-branches
      uses: mikefarah/yq@master
      with:
        cmd: "yq --no-colors --output-format=json \\\n  '[ .versions[].branch | select(.\
          \ != \"main\") ]' \\\n  version-info.toml\n"
  update:
    name: Trigger update on ${{ matrix.branch }}
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(needs.prepare.outputs.branches) }}
    steps:
    - name: workflow dispatch
      env:
        GH_TOKEN: ${{ github.token }}
        repo: ${{ github.repository }}
        branch: ${{ matrix.branch }}
      run: "gh --repo \"$repo\" workflow run \\\n  update.yml --ref \"$branch\"\n"
